### ISSUE TITLE
q请问为什么我拉下来的库，生成的出入页面，上下都没有横线？

### ISSUE THREAD

**Issue by xinkee** [21wang12/zzugo#2]
<img width="297" alt="微信截图_20210729101808" src="https://user-images.githubusercontent.com/37695244/127421391-f11f5c2f-43bd-4bff-9d03-63bea6afbcad.png">
<img width="284" alt="微信截图_20210729101920" src="https://user-images.githubusercontent.com/37695244/127421396-9ad20dc6-23e9-4960-b34b-eb2d3f91e609.png">

**Comment by 21wang12** [comment]
该横线图片的路径为`/zzugo/images/split5.png`，请在源码中将该路径替换为你所部署的路径。

**Comment by xinkee** [comment]
OJBK,感谢
