### ISSUE TITLE
二维码失效啦大佬，学校系统更新了

### ISSUE THREAD

**Issue by Edward7Bling** [21wang12/zzugo#3]
大佬救救进不去出不来的uu们吧，疫情期间管理太严啦

**Comment by lagelangrili** [comment]
是的哎，跪求大神更新

**Comment by 21wang12** [comment]
请提供一份校门口的二维码，我对照着新的系统修改一下

**Comment by Edward7Bling** [comment]
![mmexport1628437625824](https://user-images.githubusercontent.com/39651899/128637795-acb068a1-530d-4015-9f55-86529b07c3f4.jpg)

**Comment by dasheng2488** [comment]
大佬，进出门的颜色还不一样，出门是紫色，进门是绿色

**Comment by 21wang12** [comment]
> 大佬，进出门的颜色还不一样，出门是purple的，进门是绿色

那把进校和出校各发一份

**Comment by dasheng2488** [comment]
> > 大佬，进出门的颜色还不一样，出门是purple的，进门是绿色
> 
> 那把进校和出校各发一份

![mmexport1628474850299](https://user-images.githubusercontent.com/43847299/128653943-5af99bb8-026e-4d4a-9956-07ec41f21547.jpg)
![mmexport1628474813432](https://user-images.githubusercontent.com/43847299/128653946-f8b40d16-2ea9-4995-af7f-2ac50232b56d.jpg)

**Comment by lagelangrili** [comment]
大哥，是不是得要扫出来之后的那个截图

**Comment by 21wang12** [comment]
> 大哥，是不是得要扫出来之后的那个截图

有没有网站源码？我毕业了，自己的账号登不上去了

**Comment by lagelangrili** [comment]
> > 大哥，是不是要扫出来之后的那个截图
> 
> 有没有网站源码？我毕业了，自己的账号登不上去了

怎么找源码，要不我把我账号给你

**Comment by lagelangrili** [comment]
> > > 大哥，是不是要扫出来之后的那个截图
> > 
> > 
> > 有没有网站源码？我毕业了，自己的账号登不上去了
> 
> 怎么找源码，要不我把我账号给你

但是我的也扫不出来，没有权限

**Comment by dasheng2488** [comment]
> > 大哥，是不是要扫出来之后的那个截图
> 
> 有没有网站源码？我毕业了，自己的账号登不上去了

我有扫出来的截图，可以吗

**Comment by 21wang12** [comment]
> > > 大哥，是不是要扫出来之后的那个截图
> > 
> > 
> > 有没有网站源码？我毕业了，自己的账号登不上去了
> 
> 我有扫出来的截图，可以吗

也可以，请发邮箱:sw3310@columbia.edu

**Comment by 21wang12** [comment]
本人现已毕业，需要一名在校生对接该项目，校区不限，专业不限。如果你对该项目有兴趣，欢迎随时联系我：sw3310@columbia.edu

**Comment by 21wang12** [comment]
> > > 大哥，是不是要扫出来之后的那个截图
> > 
> > 
> > 有没有网站源码？我毕业了，自己的账号登不上去了
> 
> 怎么找源码，要不我把我账号给你

可以的，将账号密码发送至：sw3310@columbia.edu

**Comment by Edward7Bling** [comment]
谢谢大佬加班加点改代码，我会好好利用zzugo复习考研的，谢谢

**Comment by 21wang12** [comment]
网站已更新
